name: Deploy React App to S3

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the React app
      - name: Build React app
        run: npm run build

      # 5. Configure AWS credentials (use GitHub secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your region

      # 6. Deploy build to S3
      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://mern-app-react-build-development/ --delete --exact-timestamps

      # ...existing code...
      - name: Refresh Auto Scaling Group
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name terraform-20260101213535124300000004 \
            --preferences '{
              "MinHealthyPercentage": 50,
              "InstanceWarmup": 300
            }' \
            --region us-west-2
      # ...existing code...